export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const FLIGHT_DELAY_LOADING = 'FLIGHT_DELAY_LOADING';
export const FLIGHT_DELAY_NOT_LOADING = 'FLIGHT_DELAY_NOT_LOADING';
export const FLIGHT_DELAY_LOADED = 'FLIGHT_DELAY_LOADED';
export const FLIGHT_DELAY_ERROR = 'FLIGHT_DELAY_ERROR';
